---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime-clone-deployment
  namespace: amazon-prime-clone
  labels:
    app: amazon-prime-clone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon-prime-clone-app
  template:
    metadata:
      labels:
        app: amazon-prime-clone-app
    spec:
      containers:
        - name: amazon-prime-clone-container
          image: amazon-prime-clone-repo
          ports:
            - containerPort: 3000
            