---
apiVersion: v1
kind: Service
metadata:
  name: amazon-prime-clone-service
  namespace: amazon-prime-clone
  labels:
    app: amazon-prime-clone-app
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: amazon-prime-clone-app
  type: LoadBalancer
